export default [
  {
    term: 'Acute pain',
    chinese: '急性疼痛',
    chinese_meaning: '突然發生且持續時間短的劇烈疼痛',
    english_meaning: 'Sudden and sharp pain lasting a short time.',
  },
  {
    term: 'Back pain/Backache',
    chinese: '背痛',
    chinese_meaning: '脊椎或背部的不適或疼痛',
    english_meaning: 'Pain or discomfort in the back or spine.',
  },
  {
    term: 'Burning pain',
    chinese: '灼熱感',
    chinese_meaning: '類似燒灼或刺熱的疼痛',
    english_meaning: 'Pain that feels hot or burning.',
  },
  {
    term: 'Blinding pain',
    chinese: '刺眼的劇痛',
    chinese_meaning: '劇烈到使人無法思考的痛',
    english_meaning: 'Extremely intense pain that overwhelms the senses.',
  },
  {
    term: 'Choking pain',
    chinese: '窒息般的疼痛',
    chinese_meaning: '使人有窒息感的胸口痛',
    english_meaning: 'Pain that feels like it restricts breathing.',
  },
  {
    term: 'Chronic pain',
    chinese: '慢性疼痛',
    chinese_meaning: '持續三個月以上的長期疼痛',
    english_meaning: 'Ongoing pain lasting for a long period.',
  },
  {
    term: 'Constant pain',
    chinese: '持續疼痛',
    chinese_meaning: '不間斷的疼痛',
    english_meaning: 'Pain that does not go away.',
  },
  {
    term: 'Crushing pain',
    chinese: '壓迫性疼痛',
    chinese_meaning: '像被重物壓住般的痛',
    english_meaning: 'Heavy, squeezing pain often linked to heart issues.',
  },
  {
    term: 'Detectable pain',
    chinese: '可感知的疼痛',
    chinese_meaning: '可以被測量或辨認的疼痛',
    english_meaning: 'Pain that can be clearly identified or localized.',
  },
  {
    term: 'Dull pain',
    chinese: '隱隱作痛',
    chinese_meaning: '不劇烈但持續的鈍痛',
    english_meaning: 'Mild, persistent pain with no sharp edge.',
  },
  {
    term: 'To dull the pain',
    chinese: '減緩疼痛',
    chinese_meaning: '使疼痛感降低',
    english_meaning: 'To reduce the intensity of pain.',
  },
  {
    term: 'Excessive pain',
    chinese: '過度疼痛',
    chinese_meaning: '超出可忍受範圍的疼痛',
    english_meaning: 'Pain that feels more intense than expected.',
  },
  {
    term: 'Extensive pain',
    chinese: '廣泛性疼痛',
    chinese_meaning: '分布範圍廣的疼痛',
    english_meaning: 'Pain that affects a large area of the body.',
  },
  {
    term: 'Fleeting pain',
    chinese: '轉瞬即逝的疼痛',
    chinese_meaning: '很快消失的短暫疼痛',
    english_meaning: 'Brief and passing pain.',
  },
  {
    term: 'Increasing pain',
    chinese: '加劇的疼痛',
    chinese_meaning: '疼痛強度逐漸增加',
    english_meaning: 'Pain that gets worse over time.',
  },
  {
    term: 'Intense pain',
    chinese: '強烈的疼痛',
    chinese_meaning: '非常劇烈的疼痛',
    english_meaning: 'Severe and overwhelming pain.',
  },
  {
    term: 'Intermittent pain',
    chinese: '間歇性疼痛',
    chinese_meaning: '時有時無的疼痛',
    english_meaning: 'Pain that comes and goes.',
  },
  {
    term: 'Irregular pain',
    chinese: '不規則疼痛',
    chinese_meaning: '沒有固定模式的疼痛',
    english_meaning: 'Pain that occurs at unpredictable times.',
  },
  {
    term: 'Mild pain',
    chinese: '輕微疼痛',
    chinese_meaning: '不太影響日常活動的疼痛',
    english_meaning: 'Slight discomfort with little interference.',
  },
  {
    term: 'Oppressive pain',
    chinese: '壓迫性疼痛',
    chinese_meaning: '像被壓住的痛感',
    english_meaning: 'Pain that feels heavy or suffocating.',
  },
  {
    term: 'Overall pain',
    chinese: '整體疼痛',
    chinese_meaning: '身體多處或整體的不適',
    english_meaning: 'Generalized body pain.',
  },
  {
    term: 'Pain and stiffness',
    chinese: '疼痛與僵硬',
    chinese_meaning: '常見於關節炎',
    english_meaning: 'Combination of pain and difficulty in movement.',
  },
  {
    term: 'Pang',
    chinese: '一陣劇痛',
    chinese_meaning: '突如其來的短促強烈痛感',
    english_meaning: 'Sudden sharp stab of pain.',
  },
  {
    term: 'Piercing pain',
    chinese: '刺穿性疼痛',
    chinese_meaning: '像針刺般銳利的疼痛',
    english_meaning: 'Very sharp pain that feels like being pierced.',
  },
  {
    term: 'Postoperative pain',
    chinese: '術後疼痛',
    chinese_meaning: '手術後產生的疼痛',
    english_meaning: 'Pain experienced after a surgery.',
  },
  {
    term: 'Searing pain',
    chinese: '灼燒痛',
    chinese_meaning: '非常劇烈且熱辣的痛',
    english_meaning: 'Very intense, burning pain.',
  },
  {
    term: 'Severe pain',
    chinese: '劇痛',
    chinese_meaning: '難以忍受的強烈疼痛',
    english_meaning: 'Very strong and unbearable pain.',
  },
  {
    term: 'Sharp pain',
    chinese: '刺痛',
    chinese_meaning: '突然發作且明顯的疼痛',
    english_meaning: 'Sudden and clearly localized pain.',
  },
  {
    term: 'Slight pain',
    chinese: '輕微疼痛',
    chinese_meaning: '可忍受且程度不高的疼痛',
    english_meaning: 'Minimal level of pain.',
  },
  {
    term: 'Stabbing pain',
    chinese: '刀割般的刺痛',
    chinese_meaning: '像被刺或割傷的疼痛',
    english_meaning: 'Sudden sharp pain that feels like being stabbed.',
  },
  {
    term: 'Stitch (side pain)',
    chinese: '側腹絞痛',
    chinese_meaning: '跑步時常出現的側腹痛',
    english_meaning: 'Sudden sharp pain in the side during exercise.',
  },
  {
    term: 'Sudden pain',
    chinese: '突發性疼痛',
    chinese_meaning: '無預警快速出現的疼痛',
    english_meaning: 'Pain that appears quickly without warning.',
  },
  {
    term: 'Throbbing pain',
    chinese: '跳痛',
    chinese_meaning: '隨心跳節奏出現的疼痛',
    english_meaning: 'Rhythmic pulsing pain.',
  },
  {
    term: 'Transient pain',
    chinese: '短暫性疼痛',
    chinese_meaning: '持續時間很短的疼痛',
    english_meaning: 'Pain that lasts briefly.',
  },
  {
    term: 'Twinge',
    chinese: '一陣刺痛',
    chinese_meaning: '突然出現的短促小痛',
    english_meaning: 'Short, sudden pain or discomfort.',
  },
];
