export default [
  {
    term: 'ADVANCE DIRECTIVE',
    chinese: '預立醫療指示',
    chinese_meaning: '病人在昏迷前預先交代的治療意願',
    english_meaning: `Legal document stating a patient's future medical preferences.`,
  },
  {
    term: 'BIOPSY',
    chinese: '切片檢查',
    chinese_meaning: '取出組織樣本以檢測是否有疾病',
    english_meaning: 'Sample of tissue taken to examine for disease.',
  },
  {
    term: 'C-SECTION',
    chinese: '剖腹產',
    chinese_meaning: '通過手術將嬰兒從子宮取出',
    english_meaning: 'Surgical delivery of a baby through the abdomen.',
  },
  {
    term: 'COLONOSCOPY',
    chinese: '大腸鏡檢查',
    chinese_meaning: '檢查大腸內部是否有異常',
    english_meaning: 'Examination of the colon using a scope.',
  },
  {
    term: 'COLPOSCOPY',
    chinese: '陰道鏡檢查',
    chinese_meaning: '檢查子宮頸與陰道',
    english_meaning: 'Magnified view of the cervix and vagina.',
  },
  {
    term: 'CORONARY ARTERY BYPASS SURGERY',
    chinese: '冠狀動脈繞道手術',
    chinese_meaning: '改善心臟血流的外科手術',
    english_meaning: 'Surgery to improve blood flow to the heart.',
  },
  {
    term: 'DEFIBRILLATOR (Implant device)',
    chinese: '去顫器（植入裝置）',
    chinese_meaning: '植入以糾正危險心律不整',
    english_meaning: 'Implanted device to correct dangerous heart rhythms.',
  },
  {
    term: 'DELIVERY',
    chinese: '分娩',
    chinese_meaning: '嬰兒的出生過程',
    english_meaning: 'The act of giving birth.',
  },
  {
    term: 'ENDOSCOPY',
    chinese: '內視鏡檢查',
    chinese_meaning: '利用管狀儀器觀察體內器官',
    english_meaning: 'Inserting a scope to look inside the body.',
  },
  {
    term: 'GASTRIC BYPASS',
    chinese: '胃繞道手術',
    chinese_meaning: '減少胃容量以幫助減重',
    english_meaning:
      'Weight loss surgery that alters the stomach and intestine.',
  },
  {
    term: 'HIP REPLACEMENT',
    chinese: '髖關節置換手術',
    chinese_meaning: '用人工關節替代受損髖關節',
    english_meaning: 'Replacing a damaged hip joint with an artificial one.',
  },
  {
    term: 'HISTERECTOMY',
    chinese: '子宮切除術',
    chinese_meaning: '切除子宮的手術',
    english_meaning: 'Surgical removal of the uterus.',
  },
  {
    term: 'KNEE REPLACEMENT',
    chinese: '膝關節置換手術',
    chinese_meaning: '更換受損的膝蓋關節',
    english_meaning: 'Surgical replacement of a knee joint.',
  },
  {
    term: 'LAPAROSCOPIC CHOLECYSTECTOMY (LAP CHOLE)',
    chinese: '腹腔鏡膽囊切除術',
    chinese_meaning: '微創方式切除膽囊',
    english_meaning: 'Minimally invasive gallbladder removal.',
  },
  {
    term: 'LASER LITHOTRIPSY',
    chinese: '雷射碎石術',
    chinese_meaning: '使用雷射分解尿路結石',
    english_meaning: 'Laser treatment to break up urinary stones.',
  },
  {
    term: 'LASIK (Laser Eye Surgery)',
    chinese: '雷射視力矯正手術',
    chinese_meaning: '利用雷射改善視力',
    english_meaning: 'Laser procedure to correct vision problems.',
  },
  {
    term: 'LUMPECTOMY',
    chinese: '腫瘤切除手術',
    chinese_meaning: '移除乳房的局部腫塊',
    english_meaning: 'Removal of a breast lump or tumor.',
  },
  {
    term: 'OPEN HEART SURGERY',
    chinese: '開心手術',
    chinese_meaning: '在心臟上進行的外科手術',
    english_meaning:
      'Surgery where the chest is opened and surgery is performed on the heart.',
  },
  {
    term: 'PACEMAKER (Implant device)',
    chinese: '心律調節器（植入裝置）',
    chinese_meaning: '植入裝置以控制心跳節奏',
    english_meaning: 'Implanted device to regulate heartbeat.',
  },
  {
    term: 'PLASTIC AND COSMETIC SURGERY',
    chinese: '整形與美容手術',
    chinese_meaning: '改善外觀或重建外型的手術',
    english_meaning: 'Surgery to improve or restore appearance.',
  },
  {
    term: 'RADIATION THERAPY',
    chinese: '放射線治療',
    chinese_meaning: '用於治療癌症的放射線療程',
    english_meaning:
      'Treatment using high-energy radiation to kill cancer cells.',
  },
  {
    term: 'REHABILITATION',
    chinese: '復健治療',
    chinese_meaning: '幫助病人恢復功能與活動能力',
    english_meaning: 'Therapy to help restore normal function.',
  },
  {
    term: 'ROOT CANAL',
    chinese: '根管治療',
    chinese_meaning: '牙髓感染的牙科手術',
    english_meaning: 'Dental procedure to treat infected tooth pulp.',
  },
  {
    term: 'SPHINCTEROTOMY',
    chinese: '括約肌切開術',
    chinese_meaning: '切開括約肌以減壓或通暢',
    english_meaning: 'Surgical cut to relieve pressure or open a passage.',
  },
  {
    term: 'SLEEP STUDY',
    chinese: '睡眠檢查',
    chinese_meaning: '檢測睡眠中的呼吸與腦波',
    english_meaning: 'Test to monitor sleep patterns and breathing.',
  },
  {
    term: 'TRACHEOSTOMY',
    chinese: '氣管造口術',
    chinese_meaning: '在氣管造開口以協助呼吸',
    english_meaning: 'Surgical opening in the neck to aid breathing.',
  },
  {
    term: 'UPPER ENDOSCOPY',
    chinese: '上消化道內視鏡檢查',
    chinese_meaning: '檢查食道、胃等上消化道',
    english_meaning: 'Scope procedure to view esophagus and stomach.',
  },
  {
    term: 'VENTILATORS',
    chinese: '呼吸機',
    chinese_meaning: '協助或取代呼吸功能的機器',
    english_meaning: 'Machine that helps or controls breathing.',
  },
  {
    term: 'WEIGHT LOSS SURGERY',
    chinese: '減重手術',
    chinese_meaning: '幫助控制體重的外科手術',
    english_meaning: 'Surgical procedures to help with weight loss.',
  },
];
