export default [
  {
    term: 'A1C BLOOD / Hemoglobin A1C',
    chinese: '糖化血紅素檢查',
    chinese_meaning: '測量過去2-3個月的平均血糖',
    english_meaning: 'Blood test showing average blood sugar over 2-3 months.',
  },
  {
    term: 'BIOPSY',
    chinese: '切片檢查',
    chinese_meaning: '取出組織樣本以檢測是否有疾病',
    english_meaning: 'Sample of tissue taken to examine for disease.',
  },
  {
    term: 'BLOOD TEST / BLOOD WORK',
    chinese: '驗血',
    chinese_meaning: '檢查血液中的健康指標',
    english_meaning: 'Tests run on blood to assess health conditions.',
  },
  {
    term: 'Blood Pressure Cuff',
    chinese: '血壓計',
    chinese_meaning: '用來測量血壓的設備',
    english_meaning: 'Device used to measure blood pressure.',
  },
  {
    term: 'Cardiac Stress Test',
    chinese: '心臟壓力測試',
    chinese_meaning: '觀察心臟在運動時的表現',
    english_meaning:
      'Test to see how the heart works under stress or exercise.',
  },
  {
    term: 'CAT SCAN - CT SCAN',
    chinese: '電腦斷層掃描',
    chinese_meaning: '利用X光拍攝身體橫截面影像',
    english_meaning:
      'Imaging method using X-rays to view cross-sections of the body.',
  },
  {
    term: 'CBC (Complete Blood Count)',
    chinese: '全血球計數',
    chinese_meaning: '檢查紅白血球與血小板數量',
    english_meaning: 'Blood test measuring red/white cells and platelets.',
  },
  {
    term: 'Cervical Biopsy',
    chinese: '子宮頸切片檢查',
    chinese_meaning: '檢查子宮頸異常細胞',
    english_meaning: 'Removing tissue from the cervix for examination.',
  },
  {
    term: 'Colonoscopy',
    chinese: '大腸鏡檢查',
    chinese_meaning: '用於檢查大腸內部',
    english_meaning: 'Test that examines the inside of the colon.',
  },
  {
    term: 'Colposcopy',
    chinese: '陰道鏡檢查',
    chinese_meaning: '檢查子宮頸與陰道的放大影像',
    english_meaning: 'Magnified exam of cervix and vagina.',
  },
  {
    term: 'CULTURE',
    chinese: '培養檢查',
    chinese_meaning: '培養細菌或病毒以找出感染源',
    english_meaning: 'Test to grow microbes to identify infection.',
  },
  {
    term: 'ECHO',
    chinese: '心臟超聲波',
    chinese_meaning: '利用超聲波檢查心臟構造與功能',
    english_meaning: 'Ultrasound of the heart to assess function.',
  },
  {
    term: 'EDG',
    chinese: '上消化道內視鏡檢查',
    chinese_meaning: '檢查食道、胃與小腸',
    english_meaning:
      'Endoscopic exam of esophagus, stomach and small intestine.',
  },
  {
    term: 'EEG',
    chinese: '腦電波檢查',
    chinese_meaning: '記錄大腦電波活動',
    english_meaning: 'Test that records brain’s electrical activity.',
  },
  {
    term: 'EKG/ECG',
    chinese: '心電圖',
    chinese_meaning: '記錄心臟的電活動',
    english_meaning: 'Test that records electrical signals in the heart.',
  },
  {
    term: 'FASTING (nothing to eat)',
    chinese: '禁食',
    chinese_meaning: '進行某些檢查前需空腹',
    english_meaning: 'No food intake before a medical test.',
  },
  {
    term: 'Glucometer',
    chinese: '血糖機',
    chinese_meaning: '用來測量血糖的儀器',
    english_meaning: 'Device used to measure blood sugar levels.',
  },
  {
    term: 'Hearing Test',
    chinese: '聽力測驗',
    chinese_meaning: '檢查聽力的敏感度與範圍',
    english_meaning: 'Test to measure hearing ability.',
  },
  {
    term: 'HIV Test (Human Immunodeficiency Virus)',
    chinese: '愛滋病病毒檢測',
    chinese_meaning: '檢查是否感染HIV病毒',
    english_meaning: 'Test for the virus that causes AIDS.',
  },
  {
    term: 'HPV Test (Human Papiloma Virus)',
    chinese: '人類乳頭瘤病毒檢測',
    chinese_meaning: '檢查是否感染HPV病毒',
    english_meaning: 'Test to detect HPV infection.',
  },
  {
    term: 'ICU (Intensive Care Unit)',
    chinese: '加護病房',
    chinese_meaning: '照護危重病患的專科病房',
    english_meaning: 'Hospital unit for critically ill patients.',
  },
  {
    term: 'IUD (Intrauterine Device)',
    chinese: '子宮內避孕器',
    chinese_meaning: '放置在子宮內的避孕裝置',
    english_meaning: 'Birth control device placed in the uterus.',
  },
  {
    term: 'INR',
    chinese: '國際標準化比率',
    chinese_meaning: '監測凝血功能的指標',
    english_meaning: 'Measure of blood clotting ability.',
  },
  {
    term: 'Lancet',
    chinese: '採血針',
    chinese_meaning: '用來刺破皮膚採血',
    english_meaning: 'Small needle to obtain a blood sample.',
  },
  {
    term: 'Mamogram',
    chinese: '乳房X光攝影',
    chinese_meaning: '檢查乳房有無腫塊',
    english_meaning: 'X-ray image of the breast for cancer screening.',
  },
  {
    term: 'MRI (Magnetic Resonance Imaging)',
    chinese: '磁力共振掃描',
    chinese_meaning: '利用磁場與無害射頻影像檢查身體',
    english_meaning: 'Imaging technique using magnets and radio waves.',
  },
  {
    term: 'Nebulizer / Nebulization',
    chinese: '噴霧器 / 噴霧治療',
    chinese_meaning: '將藥物轉為霧狀進行吸入治療',
    english_meaning: 'Device that delivers medication as a mist to inhale.',
  },
  {
    term: 'PAP Smear',
    chinese: '子宮頸抹片檢查',
    chinese_meaning: '篩檢子宮頸癌',
    english_meaning: 'Screening test for cervical cancer.',
  },
  {
    term: 'PET Scan',
    chinese: '正子掃描',
    chinese_meaning: '用於檢查癌症與代謝異常',
    english_meaning: 'Imaging test to look for diseases like cancer.',
  },
  {
    term: 'PH Study and Manometry',
    chinese: '酸鹼值與壓力測試',
    chinese_meaning: '評估食道酸鹼與壓力變化',
    english_meaning: 'Measures acid and pressure in the esophagus.',
  },
  {
    term: 'PMS (Premenstrual Syndrome)',
    chinese: '經前症候群',
    chinese_meaning: '女性經期前的生理與情緒變化',
    english_meaning:
      'Symptoms before menstruation like mood swings and cramps.',
  },
  {
    term: 'STD (Sexually Transmitted Disease)',
    chinese: '性傳染病',
    chinese_meaning: '透過性行為傳播的疾病',
    english_meaning: 'Diseases spread through sexual contact.',
  },
  {
    term: 'TB Test (Tuberculosis Test)',
    chinese: '結核病檢查',
    chinese_meaning: '檢查是否感染結核桿菌',
    english_meaning: 'Test to detect tuberculosis infection.',
  },
  {
    term: 'Test Strips',
    chinese: '試紙條',
    chinese_meaning: '用於血糖等生理數值的快速測試',
    english_meaning: 'Strips used in meters to test glucose or other levels.',
  },
  {
    term: 'PKU (Phenylketonuria)',
    chinese: '苯酮尿症篩檢',
    chinese_meaning: '新生兒代謝疾病的檢測',
    english_meaning: 'Newborn screening test for a rare genetic disorder.',
  },
];
